; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


;  we must make it to the C with the framework for espidf, the arduino framewok it outdated to version 5.5 and below 

[env:esp32dev]
platform = espressif32
framework = espidf
board = esp32dev

; Force PlatformIO to download and use ESP-IDF stable v6.1
platform_packages =
    framework-espidf @ 4.60100.0